//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.DirectorServicios.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuanAnexos
    {
        public int idFuan { get; set; }
        public int totalAnexo56FuanAnexos { get; set; }
        public Nullable<int> totalAnexo56CNFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56RCFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56TIFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56CCFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56PAFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56CEFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56CDFuanAnexos { get; set; }
        public Nullable<int> totalAnexo56CSFuanAnexos { get; set; }
        public string anexo57 { get; set; }
        public string anexo58 { get; set; }
        public string anexo59 { get; set; }
        public string anexo60 { get; set; }
        public string anexo61 { get; set; }
        public string anexo62 { get; set; }
        public string anexo63 { get; set; }
        public string anexo64 { get; set; }
        public string anexo65 { get; set; }
    
        public virtual Fuan Fuan { get; set; }
    }
}
