//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coomuce.DirectorServicios.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coomuce.DirectorServicios.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales de autenticación COOMUCE.
        /// </summary>
        internal static string AsuntoCorreoCredenciales {
            get {
                return ResourceManager.GetString("AsuntoCorreoCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha activo / desactivo la compañia correctamente..
        /// </summary>
        internal static string CompañiaActivarDesactivar {
            get {
                return ResourceManager.GetString("CompañiaActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizo el envio de las credenciales a la dirección de correo especificada..
        /// </summary>
        internal static string CredencialesEnviadas {
            get {
                return ResourceManager.GetString("CredencialesEnviadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presento un error en el envio de las credenciales al correo electronico, intente reenviarla nuevamente desde la pantalla listado de usuarios..
        /// </summary>
        internal static string CredencialesNoEnviadas {
            get {
                return ResourceManager.GetString("CredencialesNoEnviadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Señor (a): &lt;b&gt;{0} {1} {2} {3}&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;Le informamos que los datos para acceder al Sistema son los siguientes: &lt;br /&gt;&lt;br /&gt;Usuario: {4}&lt;br /&gt;Contraseña: {5}&lt;br /&gt;&lt;br /&gt;Para que su usuario sea activado debe cambiar su contraseña cuando inicie sesión la primera vez.&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Cordialmente,&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;&lt;b&gt;DISOLINF&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;&lt;p&gt;Este es un mensaje generado automáticamente, por favor no responda a esta dirección de correo. En caso de requerir información adicional por favor comuníques [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CuerpoCorreoCredenciales {
            get {
                return ResourceManager.GetString("CuerpoCorreoCredenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos eliminados correctamente..
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error, comuniquese con soporte informatico.&lt;br /&gt;{0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos guardados correctamente..
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú construido correctamente..
        /// </summary>
        internal static string MenuConstruido {
            get {
                return ResourceManager.GetString("MenuConstruido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha activo / desactivo el usuario correctamente..
        /// </summary>
        internal static string UsuarioActivarDesactivar {
            get {
                return ResourceManager.GetString("UsuarioActivarDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se ha autenticado correctamente..
        /// </summary>
        internal static string UsuarioAutenticado {
            get {
                return ResourceManager.GetString("UsuarioAutenticado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña cambiada correctamente..
        /// </summary>
        internal static string UsuarioCambiarContraseña {
            get {
                return ResourceManager.GetString("UsuarioCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada es incorrecta..
        /// </summary>
        internal static string UsuarioClaveIncorrecta {
            get {
                return ResourceManager.GetString("UsuarioClaveIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado tiene clave temporal debe realizar el cambio para que el usuario se active y poder ingresar al sistema..
        /// </summary>
        internal static string UsuarioClaveTemporal {
            get {
                return ResourceManager.GetString("UsuarioClaveTemporal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra inactivo..
        /// </summary>
        internal static string UsuarioInactivo {
            get {
                return ResourceManager.GetString("UsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o contraseña ingresado son incorrectos..
        /// </summary>
        internal static string UsuarioIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña de usuario correcta..
        /// </summary>
        internal static string UsuarioReingresado {
            get {
                return ResourceManager.GetString("UsuarioReingresado", resourceCulture);
            }
        }
    }
}
